# Generated by Django 6.0.1 on 2026-02-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic.jpg', upload_to='profile_pictures'),
        ),
    ]
