# Generated by Django 6.0.1 on 2026-02-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='food_image',
            field=models.CharField(default='https://metropizza.com.au/wp-content/uploads/2023/06/food-placeholder.jpeg', max_length=255),
        ),
    ]
