# Generated by Django 6.0.1 on 2026-03-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_image_profile_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='food_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
