# Generated by Django 6.0.1 on 2026-02-23 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='food_image',
            field=models.ImageField(default='https://metropizza.com.au/wp-content/uploads/2023/06/food-placeholder.jpeg', upload_to=''),
        ),
    ]
