# Generated by Django 6.0.1 on 2026-03-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item_created_at_item_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='food_image',
            field=models.URLField(default='https://metropizza.com.au/wp-content/uploads/2023/06/food-placeholder.jpeg'),
        ),
        migrations.AlterField(
            model_name='item',
            name='food_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='food_price',
            field=models.IntegerField(db_index=True),
        ),
    ]
