# Generated by Django 6.0.1 on 2026-03-06 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_item_food_image_alter_item_food_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['food_name', 'food_price'], name='myapp_item_food_na_975760_idx'),
        ),
    ]
